# Generated by Django 3.0.6 on 2020-06-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='user_categories',
            new_name='categories',
        ),
    ]
