# Generated by Django 3.0.6 on 2020-06-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_ddd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ddd',
        ),
    ]
