# Generated by Django 3.0.6 on 2020-06-19 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_delete_ddd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('gains', models.TextField(blank=True, null=True)),
                ('includes', models.CharField(max_length=200)),
                ('scat_id', models.IntegerField(max_length=111)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('course_id', models.IntegerField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='VideoUploads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('section_id', models.IntegerField(max_length=111)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
