# Generated by Django 3.0.6 on 2020-06-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
    ]
