# Generated by Django 3.0.6 on 2020-06-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_delete_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=200)),
                ('section_id', models.IntegerField(max_length=111)),
                ('aw_1_type', models.CharField(max_length=200)),
                ('aw_1_result', models.CharField(max_length=200)),
                ('aw_1_data', models.TextField(blank=True, null=True)),
                ('aw_2_type', models.CharField(max_length=200)),
                ('aw_2_result', models.CharField(max_length=200)),
                ('aw_2_data', models.TextField(blank=True, null=True)),
                ('aw_3_type', models.CharField(max_length=200)),
                ('aw_3_result', models.CharField(max_length=200)),
                ('aw_3_data', models.TextField(blank=True, null=True)),
                ('aw_4_type', models.CharField(max_length=200)),
                ('aw_4_result', models.CharField(max_length=200)),
                ('aw_4_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
