# Generated by Django 3.0.6 on 2020-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='user_id',
            field=models.IntegerField(default=0, max_length=111),
        ),
        migrations.AddField(
            model_name='sections',
            name='type',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
