# Generated by Django 3.0.6 on 2020-06-15 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200615_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_subcategories',
            name='user_categories',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 4, 29, 58, 386542, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.DeleteModel(
            name='user_categories',
        ),
        migrations.DeleteModel(
            name='user_subcategories',
        ),
    ]
