# Generated by Django 3.0.6 on 2020-06-15 04:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('home', '0011_auto_20200615_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 4, 44, 7, 658778, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
    ]
