# Generated by Django 3.0.6 on 2020-06-15 08:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200615_0812'),
        ('home', '0013_auto_20200615_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.subcategories')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 8, 12, 16, 488070, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.DeleteModel(
            name='user_otherinfo',
        ),
        migrations.AddField(
            model_name='user_categories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
