# Generated by Django 3.0.6 on 2020-06-18 01:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200615_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 1, 48, 41, 158795, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user_categories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
