# Generated by Django 3.0.6 on 2020-06-18 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200618_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 1, 49, 57, 801552, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
