# Generated by Django 3.0.6 on 2020-06-19 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200618_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 19, 20, 13, 502184, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
