# Generated by Django 3.0.6 on 2020-06-20 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200620_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 6, 27, 7, 343351, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
