# Generated by Django 3.0.6 on 2020-06-22 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200623_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 16, 54, 47, 468644, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
