# Generated by Django 3.0.6 on 2020-06-24 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200623_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(max_length=111)),
                ('bio', models.TextField(blank=True, null=True)),
                ('cat_id', models.IntegerField(max_length=111)),
                ('subcat_ids', models.CharField(max_length=200)),
                ('facebook_url', models.CharField(max_length=200)),
                ('instagram_url', models.CharField(max_length=200)),
                ('twitter_url', models.CharField(max_length=200)),
                ('website_url', models.CharField(max_length=200)),
                ('notification', models.BooleanField(default=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 8, 27, 43, 333061, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
