# Generated by Django 3.0.6 on 2020-06-24 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200624_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 8, 29, 4, 235788, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
