# Generated by Django 3.0.6 on 2020-06-24 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20200624_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_id',
            field=models.IntegerField(default=0, max_length=111),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 8, 30, 26, 819055, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
